### ISSUE TITLE
Where is the batch_size?

### ISSUE THREAD

**Issue by vict0rsch** [cc-ai/MaskGenerator#24]
I see all inputs in `set_input_display` are unsqueezed. Why is that? Don't they come in the shape `batch x channels x height x width`? 

Why is there a need for `self.image = input.data.x.unsqueeze(0)`?

**Comment by melisandeteng** [comment]
This unsqueeze step might be unnecessary since it seems we  unsqueeze and then take the first element.
`set_input_display` is made to work for one image element (there is a for loop when plotting). This might be a result of working on top of previous code without changing it. I'll see what I can do about it.

**Comment by melisandeteng** [comment]
But indeed there is no `batch_size` when doing `__getitem__`

**Comment by vict0rsch** [comment]
ooooh `set_input_display` is not `set_input` my bad
